###
## creando nuevo usuario incorrecto
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "prueba",
    "email": "@",
    "password": "a",
    "roles": ["admin"]
}

###
## creando nuevo usuario
POST http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "edu",
    "nombre": "Edu Valls",
    "email": "eduvalls@gmail.com",
    "password": "NoTeLoDigo@1",
    "roles": ["admin"]
}

###
## login ok
POST http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "edu",
    "password": "NoTeLoDigo@1"
}

###
##  con JWGT (admin)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodWdvIiwiaWF0IjoxNzA2ODcwODM1LCJleHAiOjE3MDY5MDY4MzV9.-nQ1bZRcsHXA20n0_G6X81mWze_1L_K_a6t7csTiQEw

###
##  con JWGT (user)
GET http://localhost:8090/api/v1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJjb3MiLCJpYXQiOjE3MDY4NzA4NTgsImV4cCI6MTcwNjkwNjg1OH0.VksIudHv8ZuVqJbtuu37wbirYwWkW5DO81WyQCIN_1s

### USUARIOS ###

###

##  getUsuarioInfoById: Para el perlfil del usuario
GET http://localhost:8090/api/v1/edu/profile HTTP/1.1 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZHUiLCJpYXQiOjE3MDc0MjA4NjQsImV4cCI6MTcwNzQ1Njg2NH0.nh3idpSvYlvIJiYymEiLzIdVlqvSUTX9NexiRKRxFw8
###

## getJugadorInfoByNickname: Para las estadisticas del jugador
GET http://localhost:8090/api/v1/edu/estadisticas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZHUiLCJpYXQiOjE3MDc0MjA4NjQsImV4cCI6MTcwNzQ1Njg2NH0.nh3idpSvYlvIJiYymEiLzIdVlqvSUTX9NexiRKRxFw8
###

## Editar el perfil de un Usuario
PUT http://localhost:8090/auth/update/edu HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZHUiLCJpYXQiOjE3MDc0MjA4NjQsImV4cCI6MTcwNzQ1Njg2NH0.nh3idpSvYlvIJiYymEiLzIdVlqvSUTX9NexiRKRxFw8

{
    "nombre": "uardet",
    "nickname": "edu",
    "email": "uardet@gmail.com",
}

###